name: "CI"
on:
  push:
    branches: [main]
    # You can even set it to run only when docs related files are updated.
    # paths:
    #   - "docs/**"
    #   - "mkdocs.yml"
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      – run: pip install –upgrade pip && pip install mkdocs
      - run: pip install mkdocstrings
      - run: mkdocs gh-deploy --force
